function(qx_apply_warnings target)
    if(MSVC)
        set(_qx_warn_flags /W4 /permissive-)
        if(QX_WERROR)
            list(APPEND _qx_warn_flags /WX)
        endif()
    else()
        set(_qx_warn_flags -Wall -Wextra -Wpedantic)
        if(QX_WERROR)
            list(APPEND _qx_warn_flags -Werror)
        endif()
    endif()
    target_compile_options(${target} PRIVATE ${_qx_warn_flags})
endfunction()
